steps:
  # Build the Docker image for your Next.js app.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/website-frontend', '.']

  # Push the Docker image to Google Container Registry (GCR).
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/website-frontend']

  # Deploy the app to Google Cloud Run.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'website-frontend'
      - '--image=gcr.io/$PROJECT_ID/website-frontend'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'

