steps:
  # build the container images
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/nextjs", "./client"]

  # push the container images to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/nextjs"]

  # Deploy container images to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "nextjs",
        "--image",
        "gcr.io/$PROJECT_ID/nextjs",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--quiet",
        "--allow-unauthenticated",
      ]
images:
  - gcr.io/$PROJECT_ID/nextjs

class Solution:
    def findMedianSortedArrays(self, nums1: List[int], nums2: List[int]) -> float:
        allNums = nums1 + nums2
        allSortedNums = sorted(allNums)
        numsLen = len(allSortedNums)
        val = None
        if numsLen % 2 == 0:
            highNum = allSortedNums[numsLen/2]
            lowNum = allSortedNums[()numsLen/2)-1]
            val = (highNum+lowNum)/2
        else:
            val = allSortedNums[numsLen/2]
        return val